height: 1080
language:
  ascii: '[\x00-\x7F]+'
  en: '[a-zA-Z]+'
  jp: '[\u30a0-\u30ff\u3040-\u309f]+'
  number: '[0-9]+'
  zh: '[\u4e00-\u9fa5]+'
operate_width: 342
rule: tyrano.yaml
slider_width: 278
translator: OpenAI
width: 2160
