<template>
    <v-card>
    <v-list density="compact" variant="elevated" min-width="200px">
        <TreeNode :date="data" :padding="false" />
    </v-list>
</v-card>
</template>

<script setup lang="ts">
import TreeNode from '@/components/TreeNode.vue'

const data = [
    [
        'file.tet',
        'file',
    ],
    [
        'plugins',
        'dir',
        [
            [
                'file.txt',
                'dir',
                [
                    [
                        'file.tet',
                        'file',
                    ],
                    [
                        'plugins',
                        'dir',
                        [
                            [
                                'file.txt',
                                'file',
                            ]
                        ]
                    ],
                    [
                        'file.tsset',
                        'file',
                    ],
                ]
            ]
        ]
    ],
    [
        'file.tsset',
        'file',
    ],
    [
        'file.tet',
        'file',
    ],
    [
        'plugins',
        'dir',
        [
            [
                'file.txt',
                'dir',
                [
                    [
                        'file.tet',
                        'file',
                    ],
                    [
                        'plugins',
                        'dir',
                        [
                            [
                                'file.txt',
                                'file',
                            ]
                        ]
                    ],
                    [
                        'file.tsset',
                        'file',
                    ],
                ]
            ]
        ]
    ],
    [
        'file.tsset',
        'file',
    ],
    [
        'file.tet',
        'file',
    ],
    [
        'plugins',
        'dir',
        [
            [
                'file.txt',
                'dir',
                [
                    [
                        'file.tet',
                        'file',
                    ],
                    [
                        'plugins',
                        'dir',
                        [
                            [
                                'file.txt',
                                'file',
                            ]
                        ]
                    ],
                    [
                        'file.tsset',
                        'file',
                    ],
                ]
            ]
        ]
    ],
    [
        'file.tsset',
        'file',
    ],
]

</script>

<style>
</style>